### ISSUE TITLE
Seeing different UIs for Day and Year section on portal on Mozilla Firefox and Google Chrome

### ISSUE THREAD

**Issue by iost** [adobe/spectrum-css#214]
![GoogleChrome](https://user-images.githubusercontent.com/10536129/60889178-22bf4a80-a261-11e9-8b84-a9ea3e041cbd.png)
![Mozilla](https://user-images.githubusercontent.com/10536129/60889179-22bf4a80-a261-11e9-9be2-bd4e80b6dd53.png)

Go to https://graduation.stage.adobe.com/ on Mozilla Firefox and Google chrome separately
Sign in with a T3 user
- T1 account creation page is seen. Look at the 'Day' and 'Year' section.
Expected Result-Same UIs for Day and Year should be seen on Google Chrome and Mozilla Firefox
Actual Result- Mozilla Firefox has clickage dropdowns for Day and year while Chrome doesn't
 
Test Data-
 T3 account used- aagoyal+E2ETeam+T3+10@org31.com 
Password- Adobe123
 
Org used- SAM_EDU2 
 
Test user admin-
Id: aagoyal+E2ETeam+TestOrg+T1@adobetest.com
Password: Adobe123#
 
*Note*
To create T3 users of your own, please follow the wiki https://wiki.corp.adobe.com/display/ETL/Utility+to+Configure+T3+Users+in+Okta
 Prior to adding them in your org, you have to first request directory and domain for T3 users either org31.com or domain6.us.
Once they __ get approved, you can add them in the org and assign products in the next tab and continue your execution with the user.
Default password for these T3 users is- Adobe123

**Comment by GarthDB** [comment]
I should be able to fix it with `-moz-appearance:textfield;`

**Comment by GarthDB** [comment]
@iost I'm not sure if we should fix this in spectrum-css or if you should fix it in your code base. It is caused by using the input `type="number"` which is good for getting the correct keyboards on mobile. Until we determine if it should be changed in spectrum-css you can add a class to these inputs and add the style declaration `-moz-appearance:textfield;` or even add it as an inline style.

**Comment by markus-sessionlab** [comment]
@GarthDB The actual problem is that it already has `-moz-appearance:textfield;` however it is being overridden by `-webkit-appearance:none !important;`

![image](https://user-images.githubusercontent.com/52657946/60953758-76d03a80-a306-11e9-9e1e-b34dc22e72e3.png)

Seeing as you already have this rule and there's just a bug in how they are applied, in my opinion it is probably best if you fixed this from the top-level

**Comment by nordanga** [comment]
@GarthDB So the actual issue seems to be that `-moz-appearance:textfield;` already exists, but is being overridden by `-webkit-appearance: none !important;`

![image](https://user-images.githubusercontent.com/52739781/60955107-d62f4a00-a308-11e9-9f4b-712056378ade.png)

In my opinion, since this merely seems to a small bug around which rule gets applied, this should probably be solved by you on the top-level

**Comment by iost** [comment]
Thanks for taking this over so quickly.
Would it be possible to get the access to the JIRA project to be able to track the progress of the story?
Thanks.

**Comment by lazd** [comment]
@iost this issue is still the best place to track progress; the JIRA issues filed are just mirrors for our internal planning.

**Comment by iost** [comment]
@lazd could you provide an update on this and an ETA for the fix?

**Comment by lazd** [comment]
@iost I just looked into this issue while working on some other Textfield-related stuff, and it seems that switching the order of `-moz-appearance` and` -webkit-appearance` fixes the issue (tested in Firefox). 

I do not see the `!important` @nordanga is referring to, however. I'll commit the fix for this and it should go out in the next release (end of next sprint).

**Comment by lazd** [comment]
Looks like this was a duplicate of #132
